language: java

sudo: false

install: true

jdk:
  - openjdk8

script:
  - ./gradlew build

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
    - '.gradle'

notifications:
  email: false